cc_binary(name = 'darts',
               srcs = ['darts.cc',
                           ],
               deps = [
                       '//base:base',
                       '//file:simple_line_reader',
                          ]
           )
cc_binary(name = 'make_darts',
               srcs = ['make_darts.cc',
                           ],
               deps = [
                 '//base:base',
                          ]
           )
cc_binary(name = 'sample',
               srcs = ['sample.cc',
                           ],
               deps = [
                 '//base:base',
                          ]
           )