mv ./ahtmlparser ./ahtmlparser
mv ./ahtmlparser/easou_ahtml_area.h ./ahtmlparser/ahtml_area.h
mv ./ahtmlparser/easou_ahtml_dtd.h ./ahtmlparser/ahtml_dtd.h
mv ./ahtmlparser/easou_ahtml_tree.cpp ./ahtmlparser/ahtml_tree.cpp
mv ./ahtmlparser/easou_ahtml_tree.h ./ahtmlparser/ahtml_tree.h
mv ./cssparser ./cssparser
mv ./cssparser/DownLoad.cpp ./cssparser/DownLoad.cpp
mv ./cssparser/DownLoad.h ./cssparser/DownLoad.h
mv ./cssparser/easou_css_dtd.cpp ./cssparser/css_dtd.cpp
mv ./cssparser/easou_css_dtd.h ./cssparser/css_dtd.h
mv ./cssparser/easou_css_nodepool.cpp ./cssparser/css_nodepool.cpp
mv ./cssparser/easou_css_nodepool.h ./cssparser/css_nodepool.h
mv ./cssparser/easou_css_parser.cpp ./cssparser/css_parser.cpp
mv ./cssparser/easou_css_parser.h ./cssparser/css_parser.h
mv ./cssparser/easou_css_parser_inner.cpp ./cssparser/css_parser_inner.cpp
mv ./cssparser/easou_css_parser_inner.h ./cssparser/css_parser_inner.h
mv ./cssparser/easou_css_pool.cpp ./cssparser/css_pool.cpp
mv ./cssparser/easou_css_pool.h ./cssparser/css_pool.h
mv ./cssparser/easou_css_utils.cpp ./cssparser/css_utils.cpp
mv ./cssparser/easou_css_utils.h ./cssparser/css_utils.h
mv ./cssparser/GlobalInfo.h ./cssparser/GlobalInfo.h
mv ./cssparser/Makefile ./cssparser/Makefile
mv ./cssparser/test ./cssparser/test
mv ./cssparser/test/easou_css_test.cpp ./cssparser/test/css_test.cpp
mv ./cssparser/test/log.conf ./cssparser/test/log.conf
mv ./cssparser/test/Makefile ./cssparser/test/Makefile
mv ./extractor ./extractor
mv ./extractor/conf ./extractor/conf
mv ./extractor/conf/mysql.conf ./extractor/conf/mysql.conf
mv ./extractor/doc ./extractor/doc
mv ./extractor/doc/releate_doc.txt ./extractor/doc/releate_doc.txt
mv ./extractor/doc/StructData.thrift ./extractor/doc/StructData.thrift
mv ./extractor/easou_extractor_com.cpp ./extractor/extractor_com.cpp
mv ./extractor/easou_extractor_com.h ./extractor/extractor_com.h
mv ./extractor/easou_extractor_content.cpp ./extractor/extractor_content.cpp
mv ./extractor/easou_extractor_content.h ./extractor/extractor_content.h
mv ./extractor/easou_extractor_mypos.cpp ./extractor/extractor_mypos.cpp
mv ./extractor/easou_extractor_mypos.h ./extractor/extractor_mypos.h
mv ./extractor/easou_extractor_stdata_bk.cpp ./extractor/extractor_stdata_bk.cpp
mv ./extractor/easou_extractor_stdata_bk.h ./extractor/extractor_stdata_bk.h
mv ./extractor/easou_extractor_stdata.cpp ./extractor/extractor_stdata.cpp
mv ./extractor/easou_extractor_stdata_db.cpp ./extractor/extractor_stdata_db.cpp
mv ./extractor/easou_extractor_stdata_db.h ./extractor/extractor_stdata_db.h
mv ./extractor/easou_extractor_stdata.h ./extractor/extractor_stdata.h
mv ./extractor/easou_extractor_stdata_video.cpp ./extractor/extractor_stdata_video.cpp
mv ./extractor/easou_extractor_stdata_video.h ./extractor/extractor_stdata_video.h
mv ./extractor/easou_extractor_template.cpp ./extractor/extractor_template.cpp
mv ./extractor/easou_extractor_template.h ./extractor/extractor_template.h
mv ./extractor/easou_extractor_title.cpp ./extractor/extractor_title.cpp
mv ./extractor/easou_extractor_title.h ./extractor/extractor_title.h
mv ./extractor/Makefile ./extractor/Makefile
mv ./extractor/test ./extractor/test
mv ./extractor/test/config.ini ./extractor/test/config.ini
mv ./extractor/test/easou_debug.cpp ./extractor/test/debug.cpp
mv ./extractor/test/Key_baike.conf ./extractor/test/Key_baike.conf
mv ./extractor/test/Key_douban.conf ./extractor/test/Key_douban.conf
mv ./extractor/test/log ./extractor/test/log
mv ./extractor/test/log.conf ./extractor/test/log.conf
mv ./extractor/test/Makefile ./extractor/test/Makefile
mv ./extractor/test/readme.txt ./extractor/test/readme.txt
mv ./extractor/test/realtitle_single.cpp ./extractor/test/realtitle_single.cpp
mv ./extractor/test/realtitle_stable.cpp ./extractor/test/realtitle_stable.cpp
mv ./extractor/test/stdata_deserial_test.cpp ./extractor/test/stdata_deserial_test.cpp
mv ./extractor/test/stdata_single_test.cpp ./extractor/test/stdata_single_test.cpp
mv ./extractor/test/stdata_stable.cpp ./extractor/test/stdata_stable.cpp
mv ./extractor/test/stdata_stable_test.cpp ./extractor/test/stdata_stable_test.cpp
mv ./extractor/test/tmplt_single_test.cpp ./extractor/test/tmplt_single_test.cpp
mv ./extractor/test/tmplt_stable_test.cpp ./extractor/test/tmplt_stable_test.cpp
mv ./extractor/thrift ./extractor/thrift
mv ./extractor/thrift/StructData_constants.cpp ./extractor/thrift/StructData_constants.cpp
mv ./extractor/thrift/StructData_constants.h ./extractor/thrift/StructData_constants.h
mv ./extractor/thrift/StructData_types.cpp ./extractor/thrift/StructData_types.cpp
mv ./extractor/thrift/StructData_types.h ./extractor/thrift/StructData_types.h
mv ./file.txt ./file.txt
mv ./htmlparser ./htmlparser
mv ./htmlparser/easou_html_attr.cpp ./htmlparser/html_attr.cpp
mv ./htmlparser/easou_html_attr.h ./htmlparser/html_attr.h
mv ./htmlparser/easou_html_constructor.cpp ./htmlparser/html_constructor.cpp
mv ./htmlparser/easou_html_constructor.h ./htmlparser/html_constructor.h
mv ./htmlparser/easou_html_doctype.cpp ./htmlparser/html_doctype.cpp
mv ./htmlparser/easou_html_doctype.h ./htmlparser/html_doctype.h
mv ./htmlparser/easou_html_dom.h ./htmlparser/html_dom.h
mv ./htmlparser/easou_html_dtd.cpp ./htmlparser/html_dtd.cpp
mv ./htmlparser/easou_html_dtd.h ./htmlparser/html_dtd.h
mv ./htmlparser/easou_html_extractor.cpp ./htmlparser/html_extractor.cpp
mv ./htmlparser/easou_html_extractor.h ./htmlparser/html_extractor.h
mv ./htmlparser/easou_html_node.cpp ./htmlparser/html_node.cpp
mv ./htmlparser/easou_html_node.h ./htmlparser/html_node.h
mv ./htmlparser/easou_html_operate.cpp ./htmlparser/html_operate.cpp
mv ./htmlparser/easou_html_operate.h ./htmlparser/html_operate.h
mv ./htmlparser/easou_html_parser.cpp ./htmlparser/html_parser.cpp
mv ./htmlparser/easou_html_parser.h ./htmlparser/html_parser.h
mv ./htmlparser/easou_html_pool.cpp ./htmlparser/html_pool.cpp
mv ./htmlparser/easou_html_pool.h ./htmlparser/html_pool.h
mv ./htmlparser/easou_html_script.cpp ./htmlparser/html_script.cpp
mv ./htmlparser/easou_html_script.h ./htmlparser/html_script.h
mv ./htmlparser/easou_html_tokenizer.cpp ./htmlparser/html_tokenizer.cpp
mv ./htmlparser/easou_html_tokenizer.h ./htmlparser/html_tokenizer.h
mv ./htmlparser/easou_html_tree.cpp ./htmlparser/html_tree.cpp
mv ./htmlparser/easou_html_tree.h ./htmlparser/html_tree.h
mv ./htmlparser/easou_xpath.cpp ./htmlparser/xpath.cpp
mv ./htmlparser/easou_xpath.h ./htmlparser/xpath.h
mv ./htmlparser/Makefile ./htmlparser/Makefile
mv ./htmlparser/queue.h ./htmlparser/queue.h
mv ./htmlparser/test ./htmlparser/test
mv ./htmlparser/test/DownLoad.cpp ./htmlparser/test/DownLoad.cpp
mv ./htmlparser/test/DownLoad.h ./htmlparser/test/DownLoad.h
mv ./htmlparser/test/easou_html_test.cpp ./htmlparser/test/html_test.cpp
mv ./htmlparser/test/GlobalInfo.h ./htmlparser/test/GlobalInfo.h
mv ./htmlparser/test/htmlparser.cpp ./htmlparser/test/htmlparser.cpp
mv ./htmlparser/test/log.conf ./htmlparser/test/log.conf
mv ./htmlparser/test/Makefile ./htmlparser/test/Makefile
mv ./htmlparser/test/make.sh ./htmlparser/test/make.sh
mv ./htmlparser/test/readme.txt ./htmlparser/test/readme.txt
mv ./htmlparser/test/test.sh ./htmlparser/test/test.sh
mv ./htmlparser/test/valgrind.sh ./htmlparser/test/valgrind.sh
mv ./htmlparser/test/xpath.cpp ./htmlparser/test/xpath.cpp
mv ./linkparser ./linkparser
mv ./linkparser/config.ini ./linkparser/config.ini
mv ./linkparser/easou_extract_blogtime.cpp ./linkparser/extract_blogtime.cpp
mv ./linkparser/easou_extract_blogtime.h ./linkparser/extract_blogtime.h
mv ./linkparser/easou_extract_time.h ./linkparser/extract_time.h
mv ./linkparser/easou_link_area.cpp ./linkparser/link_area.cpp
mv ./linkparser/easou_link_area.h ./linkparser/link_area.h
mv ./linkparser/easou_link_common.cpp ./linkparser/link_common.cpp
mv ./linkparser/easou_link_common.h ./linkparser/link_common.h
mv ./linkparser/easou_link.cpp ./linkparser/link.cpp
mv ./linkparser/easou_link.h ./linkparser/link.h
mv ./linkparser/easou_link_mark.h ./linkparser/link_mark.h
mv ./linkparser/easou_link_timematch.cpp ./linkparser/link_timematch.cpp
mv ./linkparser/easou_link_timematch.h ./linkparser/link_timematch.h
mv ./linkparser/easou_link_tree.h ./linkparser/link_tree.h
mv ./linkparser/easou_linktype_bbsre.cpp ./linkparser/linktype_bbsre.cpp
mv ./linkparser/easou_linktype_blogmain.cpp ./linkparser/linktype_blogmain.cpp
mv ./linkparser/easou_linktype_blogre.cpp ./linkparser/linktype_blogre.cpp
mv ./linkparser/easou_linktype_cont_interlude.cpp ./linkparser/linktype_cont_interlude.cpp
mv ./linkparser/easou_linktype_copyright.cpp ./linkparser/linktype_copyright.cpp
mv ./linkparser/easou_linktype_css.cpp ./linkparser/linktype_css.cpp
mv ./linkparser/easou_linktype_embed_src.cpp ./linkparser/linktype_embed_src.cpp
mv ./linkparser/easou_linktype_friend.cpp ./linkparser/linktype_friend.cpp
mv ./linkparser/easou_linktype_friendex.cpp ./linkparser/linktype_friendex.cpp
mv ./linkparser/easou_linktype_hidden.cpp ./linkparser/linktype_hidden.cpp
mv ./linkparser/easou_linktype_iframe.cpp ./linkparser/linktype_iframe.cpp
mv ./linkparser/easou_linktype_image.cpp ./linkparser/linktype_image.cpp
mv ./linkparser/easou_linktype_img_src.cpp ./linkparser/linktype_img_src.cpp
mv ./linkparser/easou_linktype_invalid_and_control.cpp ./linkparser/linktype_invalid_and_control.cpp
mv ./linkparser/easou_linktype_mypos.cpp ./linkparser/linktype_mypos.cpp
mv ./linkparser/easou_linktype_nav.cpp ./linkparser/linktype_nav.cpp
mv ./linkparser/easou_linktype_nofollow.cpp ./linkparser/linktype_nofollow.cpp
mv ./linkparser/easou_linktype_quotation.cpp ./linkparser/linktype_quotation.cpp
mv ./linkparser/easou_linktype_selfhelp.cpp ./linkparser/linktype_selfhelp.cpp
mv ./linkparser/easou_linktype_text.cpp ./linkparser/linktype_text.cpp
mv ./linkparser/Makefile ./linkparser/Makefile
mv ./linkparser/test ./linkparser/test
mv ./linkparser/test/basic.mk ./linkparser/test/basic.mk
mv ./linkparser/test/config.ini ./linkparser/test/config.ini
mv ./linkparser/test/css_selector.txt ./linkparser/test/css_selector.txt
mv ./linkparser/test/DownLoad.cpp ./linkparser/test/DownLoad.cpp
mv ./linkparser/test/DownLoad.h ./linkparser/test/DownLoad.h
mv ./linkparser/test/easou_linkparser_test.cpp ./linkparser/test/linkparser_test.cpp
mv ./linkparser/test/extract_img_infos.cpp ./linkparser/test/extract_img_infos.cpp
mv ./linkparser/test/extract_news_img.cpp ./linkparser/test/extract_news_img.cpp
mv ./linkparser/test/GlobalInfo.h ./linkparser/test/GlobalInfo.h
mv ./linkparser/test/img_stable.cpp ./linkparser/test/img_stable.cpp
mv ./linkparser/test/local_img.csv ./linkparser/test/local_img.csv
mv ./linkparser/test/log ./linkparser/test/log
mv ./linkparser/test/log/MS_batchread ./linkparser/test/log/MS_batchread
mv ./linkparser/test/log/WR_batchread ./linkparser/test/log/WR_batchread
mv ./linkparser/test/log/WR_batchread.1 ./linkparser/test/log/WR_batchread.1
mv ./linkparser/test/log.conf ./linkparser/test/log.conf
mv ./linkparser/test/Makefile ./linkparser/test/Makefile
mv ./linkparser/test/makerunonpagedb.sh ./linkparser/test/makerunonpagedb.sh
mv ./linkparser/test/news.lst ./linkparser/test/news.lst
mv ./linkparser/test/pagetranslate.h ./linkparser/test/pagetranslate.h
mv ./linkparser/test/readme.txt ./linkparser/test/readme.txt
mv ./linkparser/test/runonpagedb.cpp ./linkparser/test/runonpagedb.cpp
mv ./markparser ./markparser
mv ./markparser/easou_lang_relate.cpp ./markparser/lang_relate.cpp
mv ./markparser/easou_lang_relate.h ./markparser/lang_relate.h
mv ./markparser/easou_mark_baseinfo.cpp ./markparser/mark_baseinfo.cpp
mv ./markparser/easou_mark_baseinfo.h ./markparser/mark_baseinfo.h
mv ./markparser/easou_mark_com.cpp ./markparser/mark_com.cpp
mv ./markparser/easou_mark_com.h ./markparser/mark_com.h
mv ./markparser/easou_mark_conf.cpp ./markparser/mark_conf.cpp
mv ./markparser/easou_mark_conf.h ./markparser/mark_conf.h
mv ./markparser/easou_mark_func.cpp ./markparser/mark_func.cpp
mv ./markparser/easou_mark_func.h ./markparser/mark_func.h
mv ./markparser/easou_mark_inner.cpp ./markparser/mark_inner.cpp
mv ./markparser/easou_mark_inner.h ./markparser/mark_inner.h
mv ./markparser/easou_mark_innerinfo.cpp ./markparser/mark_innerinfo.cpp
mv ./markparser/easou_mark_innerinfo.h ./markparser/mark_innerinfo.h
mv ./markparser/easou_mark_markinfo.cpp ./markparser/mark_markinfo.cpp
mv ./markparser/easou_mark_markinfo.h ./markparser/mark_markinfo.h
mv ./markparser/easou_mark_parser.cpp ./markparser/mark_parser.cpp
mv ./markparser/easou_mark_parser.h ./markparser/mark_parser.h
mv ./markparser/easou_mark_pos.cpp ./markparser/mark_pos.cpp
mv ./markparser/easou_mark_pos.h ./markparser/mark_pos.h
mv ./markparser/easou_mark_sem.cpp ./markparser/mark_sem.cpp
mv ./markparser/easou_mark_sem.h ./markparser/mark_sem.h
mv ./markparser/easou_mark_srctype.cpp ./markparser/mark_srctype.cpp
mv ./markparser/easou_mark_srctype.h ./markparser/mark_srctype.h
mv ./markparser/easou_mark_switch.cpp ./markparser/mark_switch.cpp
mv ./markparser/easou_mark_switch.h ./markparser/mark_switch.h
mv ./markparser/Makefile ./markparser/Makefile
mv ./markparser/mark_function ./markparser/mark_function
mv ./markparser/mark_function/mark_func_article_content.cpp ./markparser/mark_function/mark_func_article_content.cpp
mv ./markparser/mark_function/mark_func_copyright.cpp ./markparser/mark_function/mark_func_copyright.cpp
mv ./markparser/mark_function/mark_func_mypos.cpp ./markparser/mark_function/mark_func_mypos.cpp
mv ./markparser/mark_function/mark_func_nav.cpp ./markparser/mark_function/mark_func_nav.cpp
mv ./markparser/mark_function/mark_func_relatelink.cpp ./markparser/mark_function/mark_func_relatelink.cpp
mv ./markparser/mark_function/mark_func_subtitforrt.cpp ./markparser/mark_function/mark_func_subtitforrt.cpp
mv ./markparser/mark_function/mark_func_time.cpp ./markparser/mark_function/mark_func_time.cpp
mv ./markparser/mark_function/mark_func_turnpage.cpp ./markparser/mark_function/mark_func_turnpage.cpp
mv ./markparser/mark_function/mark_mark_articlesign.cpp ./markparser/mark_function/mark_mark_articlesign.cpp
mv ./markparser/mark_function/mark_mark_friend.cpp ./markparser/mark_function/mark_mark_friend.cpp
mv ./markparser/mark_function/mark_mark_subtitle.cpp ./markparser/mark_function/mark_mark_subtitle.cpp
mv ./markparser/mark_function/mark_sem_central.cpp ./markparser/mark_function/mark_sem_central.cpp
mv ./markparser/mark_function/mark_sem_hub_content.cpp ./markparser/mark_function/mark_sem_hub_content.cpp
mv ./markparser/mark_function/mark_sem_realtitle.cpp ./markparser/mark_function/mark_sem_realtitle.cpp
mv ./markparser/mark_function/mark_srctype_interaction.cpp ./markparser/mark_function/mark_srctype_interaction.cpp
mv ./markparser/mark_function/mark_srctype_link.cpp ./markparser/mark_function/mark_srctype_link.cpp
mv ./markparser/mark_function/mark_srctype_others.cpp ./markparser/mark_function/mark_srctype_others.cpp
mv ./markparser/mark_function/mark_srctype_picture.cpp ./markparser/mark_function/mark_srctype_picture.cpp
mv ./markparser/test ./markparser/test
mv ./markparser/test/2.html ./markparser/test/2.html
mv ./markparser/test/config.ini ./markparser/test/config.ini
mv ./markparser/test/DownLoad.cpp ./markparser/test/DownLoad.cpp
mv ./markparser/test/DownLoad.h ./markparser/test/DownLoad.h
mv ./markparser/test/easou_mark_test.cpp ./markparser/test/mark_test.cpp
mv ./markparser/test/GlobalInfo.h ./markparser/test/GlobalInfo.h
mv ./markparser/test/log ./markparser/test/log
mv ./markparser/test/log.conf ./markparser/test/log.conf
mv ./markparser/test/Makefile ./markparser/test/Makefile
mv ./markparser/test/readme.txt ./markparser/test/readme.txt
mv ./markparser/test/test.sh ./markparser/test/test.sh
mv ./readme.txt ./readme.txt
mv ./test ./test
mv ./test/addtomysql.cpp ./test/addtomysql.cpp
mv ./test/area_visual_tool.cpp ./test/area_visual_tool.cpp
mv ./test/area_visual_tool.h ./test/area_visual_tool.h
mv ./test/config.ini ./test/config.ini
mv ./test/cored_pages ./test/cored_pages
mv ./test/cored_pages/1.html ./test/cored_pages/1.html
mv ./test/cored_pages/2.html ./test/cored_pages/2.html
mv ./test/cored_pages/url.lst ./test/cored_pages/url.lst
mv ./test/dbReader ./test/dbReader
mv ./test/diff_tool ./test/diff_tool
mv ./test/diff_tool/add_marked_realtitle.cpp ./test/diff_tool/add_marked_realtitle.cpp
mv ./test/diff_tool/Makefile ./test/diff_tool/Makefile
mv ./test/diff_tool/MarkedRealtitleReader.cpp ./test/diff_tool/MarkedRealtitleReader.cpp
mv ./test/diff_tool/MarkedRealtitleReader.h ./test/diff_tool/MarkedRealtitleReader.h
mv ./test/diff_tool/parser_server.cpp ./test/diff_tool/parser_server.cpp
mv ./test/diff_tool/parse.thrift ./test/diff_tool/parse.thrift
mv ./test/diff_tool/realtitle_marked_diff.cpp ./test/diff_tool/realtitle_marked_diff.cpp
mv ./test/diff_tool/report_diff.cpp ./test/diff_tool/report_diff.cpp
mv ./test/diff_tool/report_diff.h ./test/diff_tool/report_diff.h
mv ./test/diff_tool/RTDiffAnalyzer.cpp ./test/diff_tool/RTDiffAnalyzer.cpp
mv ./test/diff_tool/RTDiffAnalyzer.h ./test/diff_tool/RTDiffAnalyzer.h
mv ./test/diff_tool/version_diff.cpp ./test/diff_tool/version_diff.cpp
mv ./test/DownLoad.cpp ./test/DownLoad.cpp
mv ./test/DownLoad.h ./test/DownLoad.h
mv ./test/dump ./test/dump
mv ./test/dump.sh ./test/dump.sh
mv ./test/easou_conv.h ./test/conv.h
mv ./test/easou_fmtcont.h ./test/fmtcont.h
mv ./test/easou_pagedb.h ./test/pagedb.h
mv ./test/easou_parse.h ./test/parse.h
mv ./test/easou_parse_test.cpp ./test/parse_test.cpp
mv ./test/easou_segtag.h ./test/segtag.h
mv ./test/easou_vhtml_utils.cpp ./test/vhtml_utils.cpp
mv ./test/easou_vhtml_utils.h ./test/vhtml_utils.h
mv ./test/filter.ini ./test/filter.ini
mv ./test/fmtcont_test.cpp ./test/fmtcont_test.cpp
mv ./test/GlobalInfo.h ./test/GlobalInfo.h
mv ./test/log ./test/log
mv ./test/log.conf ./test/log.conf
mv ./test/Makefile ./test/Makefile
mv ./test/makeparser.sh ./test/makeparser.sh
mv ./test/makerunoffpagedb.sh ./test/makerunoffpagedb.sh
mv ./test/makerunonpagedb.sh ./test/makerunonpagedb.sh
mv ./test/make.sh ./test/make.sh
mv ./test/pagetranslate.h ./test/pagetranslate.h
mv ./test/parser.cpp ./test/parser.cpp
mv ./test/parser_lst.cpp ./test/parser_lst.cpp
mv ./test/parser_lst.sh ./test/parser_lst.sh
mv ./test/readme.txt ./test/readme.txt
mv ./test/runoffpagedb.cpp ./test/runoffpagedb.cpp
mv ./test/runonmysql.cpp ./test/runonmysql.cpp
mv ./test/runonpagedb.cpp ./test/runonpagedb.cpp
mv ./test/start_listen.sh ./test/start_listen.sh
mv ./test/tool_global.cpp ./test/tool_global.cpp
mv ./test/tool_global.h ./test/tool_global.h
mv ./test/viewcentral.cpp ./test/viewcentral.cpp
mv ./test/viewpage.cpp ./test/viewpage.cpp
mv ./test/viewtestset.cpp ./test/viewtestset.cpp
mv ./utils ./utils
mv ./utils/bootstrap.cpp ./utils/bootstrap.cpp
mv ./utils/bootstrap.fr.seed ./utils/bootstrap.fr.seed
mv ./utils/bootstrap.h ./utils/bootstrap.h
mv ./utils/chinese.h ./utils/chinese.h
mv ./utils/debuginfo.h ./utils/debuginfo.h
mv ./utils/easou_common_utils.cpp ./utils/common_utils.cpp
mv ./utils/easou_common_utils.h ./utils/common_utils.h
mv ./utils/easou_debug.cpp ./utils/debug.cpp
mv ./utils/easou_debug.h ./utils/debug.h
mv ./utils/easou_string.cpp ./utils/string.cpp
mv ./utils/easou_string.h ./utils/string.h
mv ./utils/easou_url.cpp ./utils/url.cpp
mv ./utils/easou_url.h ./utils/url.h
mv ./utils/html_text_utils.cpp ./utils/html_text_utils.cpp
mv ./utils/html_text_utils.h ./utils/html_text_utils.h
mv ./utils/id_map.cpp ./utils/id_map.cpp
mv ./utils/id_map.h ./utils/id_map.h
mv ./utils/include ./utils/include
mv ./utils/include/bootstrap.h ./utils/include/bootstrap.h
mv ./utils/include/chinese.h ./utils/include/chinese.h
mv ./utils/include/debuginfo.h ./utils/include/debuginfo.h
mv ./utils/include/easou_common_utils.h ./utils/include/common_utils.h
mv ./utils/include/easou_debug.h ./utils/include/debug.h
mv ./utils/include/easou_string.h ./utils/include/string.h
mv ./utils/include/easou_url.h ./utils/include/url.h
mv ./utils/include/html_text_utils.h ./utils/include/html_text_utils.h
mv ./utils/include/id_map.h ./utils/include/id_map.h
mv ./utils/include/nodepool.h ./utils/include/nodepool.h
mv ./utils/include/simplehashmap.h ./utils/include/simplehashmap.h
mv ./utils/include/u.h ./utils/include/u.h
mv ./utils/lib ./utils/lib
mv ./utils/lib/libutils.a ./utils/lib/libutils.a
mv ./utils/lib/libutils_debug.a ./utils/lib/libutils_debug.a
mv ./utils/lib/libutils_dump.a ./utils/lib/libutils_dump.a
mv ./utils/lib/libutils_time.a ./utils/lib/libutils_time.a
mv ./utils/Makefile ./utils/Makefile
mv ./utils/nodepool.cpp ./utils/nodepool.cpp
mv ./utils/nodepool.h ./utils/nodepool.h
mv ./utils/simplehashmap.cpp ./utils/simplehashmap.cpp
mv ./utils/simplehashmap.h ./utils/simplehashmap.h
mv ./utils/u.h ./utils/u.h
mv ./vhtmlparser ./vhtmlparser
mv ./vhtmlparser/easou_vhtml_basic.cpp ./vhtmlparser/vhtml_basic.cpp
mv ./vhtmlparser/easou_vhtml_basic.h ./vhtmlparser/vhtml_basic.h
mv ./vhtmlparser/easou_vhtml_dtd.h ./vhtmlparser/vhtml_dtd.h
mv ./vhtmlparser/easou_vhtml_inner.cpp ./vhtmlparser/vhtml_inner.cpp
mv ./vhtmlparser/easou_vhtml_inner.h ./vhtmlparser/vhtml_inner.h
mv ./vhtmlparser/easou_vhtml_parser.cpp ./vhtmlparser/vhtml_parser.cpp
mv ./vhtmlparser/easou_vhtml_parser.h ./vhtmlparser/vhtml_parser.h
mv ./vhtmlparser/easou_vhtml_tree.cpp ./vhtmlparser/vhtml_tree.cpp
mv ./vhtmlparser/easou_vhtml_tree.h ./vhtmlparser/vhtml_tree.h
mv ./vhtmlparser/easou_vhtml_utils.cpp ./vhtmlparser/vhtml_utils.cpp
mv ./vhtmlparser/easou_vhtml_utils.h ./vhtmlparser/vhtml_utils.h
mv ./vhtmlparser/easou_vstruct_profiler.cpp ./vhtmlparser/vstruct_profiler.cpp
mv ./vhtmlparser/easou_vstruct_profiler.h ./vhtmlparser/vstruct_profiler.h
mv ./vhtmlparser/test ./vhtmlparser/test
mv ./vhtmlparser/test/DownLoad.cpp ./vhtmlparser/test/DownLoad.cpp
mv ./vhtmlparser/test/DownLoad.h ./vhtmlparser/test/DownLoad.h
mv ./vhtmlparser/test/easou_vhtml_test.cpp ./vhtmlparser/test/vhtml_test.cpp
mv ./vhtmlparser/test/GlobalInfo.h ./vhtmlparser/test/GlobalInfo.h
mv ./vhtmlparser/test/log.conf ./vhtmlparser/test/log.conf
mv ./vhtmlparser/test/Makefile ./vhtmlparser/test/Makefile
mv ./vhtmlparser/test/parser_32test.sh ./vhtmlparser/test/parser_32test.sh
mv ./vhtmlparser/test/parser.cpp ./vhtmlparser/test/parser.cpp
mv ./vhtmlparser/test/parser_test.sh ./vhtmlparser/test/parser_test.sh
mv ./vhtmlparser/test/readme.txt ./vhtmlparser/test/readme.txt
mv ./vhtmlparser/test/vtree_print_utils.cpp ./vhtmlparser/test/vtree_print_utils.cpp
mv ./vhtmlparser/test/vtree_print_utils.h ./vhtmlparser/test/vtree_print_utils.h
