cc_library(name = 'vhtmlparser',
    srcs = [
        'vhtml_basic.cpp',
        'vhtml_inner.cpp',
        'vhtml_parser.cpp',
        'vhtml_tree.cpp',
        'vhtml_utils.cpp',
        'vstruct_profiler.cpp'
    ],
    warning = 'no',
)
