#!/bin/bash --norc
#
# Automatically generate boilerplate code by looking at the file
# name.
#
# Note: When the file type cannot be determined, the output must have a
#       specific format so that programs depending on this script can match it.
#       For example, google.el looks for '^Unknown' in the output to determine
#       if this script succeeded.
#

usage() {
cat <<EOF

Usage: `basename $0` source-file-name

EOF
  exit 1
}

# Parse positional arguments
if [ $# -ne 1 ]; then
  usage
fi

filename="$1"
scriptdir=`dirname $0`

# Resolve the full path to the file. If the directory can't be resolved, don't
# look for AUTOGEN files.
search_pathname=$(cd "$(dirname $filename)" > /dev/null 2>&1 && pwd) && {
relative_pathname="$search_pathname/$(basename $filename)"
relative_pathname=${relative_pathname/*?}
  until [ "$search_pathname" == "/" ]; do
    if [ -r "$search_pathname/AUTOGEN" ]; then
      SCRIPT_DIR=$scriptdir "$search_pathname/AUTOGEN" "$relative_pathname" && exit
    fi
    search_pathname="$(dirname $search_pathname)"
  done
}

case "$filename" in
  *_test.cc)     "$scriptdir/gencunit" "$filename" ;;
  *_regtest.cc)  "$scriptdir/gencunit" "$filename" ;;
  *_unittest.cc) "$scriptdir/gencunit" "$filename" ;;
  *_main.cc)     "$scriptdir/gencmain" "$filename" ;;
  *.h)           "$scriptdir/genc" "$filename" ;;
  *.cc)          "$scriptdir/genc" "$filename" ;;
  *.thrift)      "$scriptdir/gboilerplate" -C "//" ;;
  *Test.java)    "$scriptdir/genjunit" "$filename" ;;
  *.java)        "$scriptdir/genj" "$filename" ;;
  *_test.js)     "$scriptdir/gboilerplate" -C "//" ;;
  *_unittest.js) "$scriptdir/gboilerplate" -C "//" ;;
  *.js)          "$scriptdir/genjs" "$filename" ;;
  *_test.py)     "$scriptdir/genpyunit" "$filename" ;;
  *_unittest.py) "$scriptdir/genpyunit" "$filename" ;;
  *.py)          "$scriptdir/genpy" "$filename" ;;
  *test.sh)      "$scriptdir/genshtest" "$filename" ;;
  *.sh)          "$scriptdir/gensh" "$filename" ;;
  *EBUILD)       "$scriptdir/genbuild" "$filename" ;;
  *.swig)        "$scriptdir/genswig" "$filename" ;;
  *AUTOGEN)      "$scriptdir/genautogen" "$filename" ;;
  *.rb)          "$scriptdir/genrb" "$filename" ;;
  *)             echo "Unknown file type for $filename" >&2; exit 1 ;;
esac
