#!/bin/bash --norc
#
# Generate a boilerplate EBUILD file to stdout

usage() {
cat <<EOF

Usage: `basename $0` directory/BUILD

EOF
  exit 1
}

# Parse positional arguments
if [ $# -ne 1 ]; then
  usage
fi

filename="$1"

if [ `basename "${filename}"` != "EBUILD" ]; then
  echo "$filename not a BUILD file"
  exit 1
fi

if [ "${filename#/}" = "$filename" ]; then
  filename="$PWD/$filename"
fi

if ! expr "$filename" : ".*/websearch/" >/dev/null; then
  echo "$filename is not beneath a directory named 'google3'."
  exit 1
fi

dirname=$(dirname $filename)
libname=$(basename $dirname)
package=$(echo "$dirname" | sed -e 's?^.*/websearch/??')

scriptdir=`dirname $0`
$scriptdir/gboilerplate -C "#"

cat <<EOF
#
# Description:
#   TODO(${USER}): describe this package.

EOF
