#!/usr/bin/python
#

"""Generate boilerplate for c++ main file.

"""

__author__ = 'yeshunping@gmail.com'

import datetime
import os
import re
import sys
from author_info import GetAuthorInfo


def main(argv):
  print '// Copyright %d. All Rights Reserved.' % (
      datetime.date.today().year)
  print '// Author: %s\n' % GetAuthorInfo()
  print '#include "base/flags.h"'
  print '#include "base/ns.h"'
  print ''
  print 'int main(int argc, char **argv) {'
  print '  google::ParseCommandLineFlags(&argc, &argv, true);'
  print ''
  print '  return 0;'
  print '}'


if __name__ == '__main__':
  main(sys.argv)

