#!/bin/bash --norc
#
# Generate a boilerplate shell script to stdout.
#

usage() {
cat <<EOF

Usage: `basename $0` shell-file

EOF
  exit 1
}

# Parse positional arguments
if [ $# -ne 1 ]; then
  usage
fi

filename="$1"

if [ "${filename%.sh}" = "$filename" ]; then
  echo "$filename doesn't end with .sh"
  exit 1
fi

# -i == include $Id$ comment, which we only enable for the ops tree
include_id_arg=""
if [ "${filename/\/ops\//}" != "$filename" ]; then
  include_id_arg="-i"
fi

scriptdir=`dirname $0`
$scriptdir/gboilerplate -s /bin/bash $include_id_arg
