#!/bin/bash --norc

echo "thrift_library(name = '')"
echo "               srcs = ["
echo "                      ],"
echo "               deps = ["
echo "                      ],"
echo "              )"
