cc_library(name = 'utils',
    srcs = [
        'common_utils.cpp',
        'debug.cpp',
        'html_text_utils.cpp',
        'id_map.cpp',
        'nodepool.cpp',
        'simplehashmap.cpp',
        'string_util.cpp',
        'url.cpp',
    ],
    warning = 'no',
    incs = ['.',],
    deps = [
            '//base:base',
            ],
)

