cc_library(name = 'utils',
    srcs = [
        'bootstrap.cpp',
        'common_utils.cpp',
        'debug.cpp',
        'html_text_utils.cpp',
        'id_map.cpp',
        'nodepool.cpp',
        'simplehashmap.cpp',
        'string_util.cpp',
        'url.cpp',
        'log.cpp',
    ],
    warning = 'no',
    incs = ['.', '../../../thirdparty/log4cpp/include',],
)

