cc_library(name = 'htmlparser',
    srcs = [
        'html_attr.cpp',
        'html_constructor.cpp',
        'html_doctype.cpp',
        'html_dtd.cpp',
        'html_extractor.cpp',
        'html_node.cpp',
        'html_operate.cpp',
        'html_parser.cpp',
        'html_pool.cpp',
        'html_script.cpp',
        'html_tokenizer.cpp',
        'html_tree.cpp',
        'xpath.cpp'
    ],
    warning = 'no',
    deps = [
            '//util/htmlparser/utils:utils',
            ],
)

