cc_library(name = 'vhtmlparser',
    srcs = [
        'ahtml_tree.cpp'
    ],
    deps = [
            '//util/htmlparser/vhtmlparser:vhtmlparser',
            '//util/htmlparser/htmlparser:htmlparser',
            '//util/htmlparser/cssparser:cssparser',
            '//util/htmlparser/utils:utils',
            ],
)

