cc_library(name = 'cssparser',
    srcs = [
        'css_dtd.cpp',
        'css_nodepool.cpp',
        'css_parser.cpp',
        'css_parser_inner.cpp',
        'css_pool.cpp',
        'css_utils.cpp',
        'DownLoad.cpp'
    ],
    warning = 'no',
)

