/**
 * @file easou_css_dtd.cpp

 * @date 2011/06/20
 * @version 1.0(create)
 * @brief	CSS类型定义
 *  
 **/

#include "css_dtd.h"

/**
 * @brief css_prop_first_char_map[i]表示以ASCII码i为首字母的CSS属性在css_property_name_array中的开始位置.
 */
short css_prop_first_char_map[] = 
{-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,0,2,34,45,47,49,-1,59,60,-1,-1,62,79,-1,109,
117,133,134,140,156,169,171,175,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1};


//border[11], border-bottom[12], cursor[44], overflow[114]
short css_other_usefull_prop[] =
{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, //0~15 border border-bottom
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, //16~31
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, //32~47
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, //48~63
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, //64~79
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, //80~95
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, //96~111
		0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, //112~127
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, //128~143
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, //144~159
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, //160~175
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, //176~191
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, //192~207
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, //208~223
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, //224~239
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, //240~255
		};

/**
 * css_property_name_array[]与prop_typeinfo_array[]每个元素一一对应
 */
const char *css_property_name_array[] =
{
	"accelerator",
	"azimuth",
	"background",
	"background-attachment",
	"background-color",
	"background-image",
	"background-position",
	"background-position-x",
	"background-position-y",
	"background-repeat",
	"behavior",
	"border",
	"border-bottom",
	"border-bottom-color",
	"border-bottom-style",
	"border-bottom-width",
	"border-collapse",
	"border-color",
	"border-left",
	"border-left-color",
	"border-left-style",
	"border-left-width",
	"border-right",
	"border-right-color",
	"border-right-style",
	"border-right-width",
	"border-spacing",
	"border-style",
	"border-top",
	"border-top-color",
	"border-top-style",
	"border-top-width",
	"border-width",
	"bottom",
	"caption-side",
	"clear",
	"clip",
	"color",
	"content",
	"counter-increment",
	"counter-reset",
	"cue",
	"cue-after",
	"cue-before",
	"cursor",
	"direction",
	"display",
	"elevation",
	"empty-cells",
	"filter",
	"float",
	"font",
	"font-family",
	"font-size",
	"font-size-adjust",
	"font-stretch",
	"font-style",
	"font-variant",
	"font-weight",
	"height",
	"ime-mode",
	"include-source",
	"layer-background-color",
	"layer-background-image",
	"layout-flow",
	"layout-grid",
	"layout-grid-char",
	"layout-grid-char-spacing",
	"layout-grid-line",
	"layout-grid-mode",
	"layout-grid-type",
	"left",
	"letter-spacing",
	"line-break",
	"line-height",
	"list-style",
	"list-style-image",
	"list-style-position",
	"list-style-type",
	"margin",
	"margin-bottom",
	"margin-left",
	"margin-right",
	"margin-top",
	"marker-offset",
	"marks",
	"max-height",
	"max-width",
	"min-height",
	"min-width",
	"-moz-binding",
	"-moz-border-bottom-colors",
	"-moz-border-left-colors",
	"-moz-border-radius",
	"-moz-border-radius-bottomleft",
	"-moz-border-radius-bottomright",
	"-moz-border-radius-topleft",
	"-moz-border-radius-topright",
	"-moz-border-right-colors",
	"-moz-border-top-colors",
	"-moz-opacity",
	"-moz-outline",
	"-moz-outline-color",
	"-moz-outline-style",
	"-moz-outline-width",
	"-moz-user-focus",
	"-moz-user-input",
	"-moz-user-modify",
	"-moz-user-select",
	"orphans",
	"outline",
	"outline-color",
	"outline-style",
	"outline-width",
	"overflow",
	"overflow-X",
	"overflow-Y",
	"padding",
	"padding-bottom",
	"padding-left",
	"padding-right",
	"padding-top",
	"page",
	"page-break-after",
	"page-break-before",
	"page-break-inside",
	"pause",
	"pause-after",
	"pause-before",
	"pitch",
	"pitch-range",
	"play-during",
	"position",
	"quotes",
	"-replace",
	"richness",
	"right",
	"ruby-align",
	"ruby-overhang",
	"ruby-position ",
	"scrollbar-3d-light-color",
	"scrollbar-arrow-color",
	"scrollbar-base-color",
	"scrollbar-dark-shadow-color",
	"scrollbar-face-color",
	"scrollbar-highlight-color",
	"scrollbar-shadow-color",
	"scrollbar-track-color",
	"-set-link-source",
	"size",
	"speak",
	"speak-header",
	"speak-numeral",
	"speak-punctuation",
	"speech-rate",
	"stress",
	"table-layout",
	"text-align",
	"text-align-last",
	"text-autospace",
	"text-decoration",
	"text-indent",
	"text-justify",
	"text-kashida-space",
	"text-overflow",
	"text-shadow",
	"text-transform",
	"text-underline-position",
	"top",
	"unicode-bidi",
	"-use-link-source",
	"vertical-align",
	"visibility",
	"voice-family",
	"volume ",
	"white-space",
	"widows",
	"width",
	"word-break",
	"word-spacing",
	"word-wrap",
	"writing-mode"
};

/* css_property_name_array[]与prop_typeinfo_array[]每个元素一一对应 */
const easou_css_prop_type_info_t prop_typeinfo_array[] =
{
/* property-type, is font property, is geo property */
/* cannot be font prop and geo prop at the same time*/
	{CSS_PROP_ACCELERATOR,0,0},
	{CSS_PROP_AZIMUTH,0,0},
	{CSS_PROP_BACKGROUND,1,0},
	{CSS_PROP_BACKGROUND_ATTACHMENT,0,0},
	{CSS_PROP_BACKGROUND_COLOR,1,0},
	{CSS_PROP_BACKGROUND_IMAGE,0,0},
	{CSS_PROP_BACKGROUND_POSITION,0,0},
	{CSS_PROP_BACKGROUND_POSITION_X,0,0},
	{CSS_PROP_BACKGROUND_POSITION_Y,0,0},
	{CSS_PROP_BACKGROUND_REPEAT,0,0},
	{CSS_PROP_BEHAVIOR,0,0},
	{CSS_PROP_BORDER,0,0},
	{CSS_PROP_BORDER_BOTTOM,0,0},
	{CSS_PROP_BORDER_BOTTOM_COLOR,0,0},
	{CSS_PROP_BORDER_BOTTOM_STYLE,0,0},
	{CSS_PROP_BORDER_BOTTOM_WIDTH,0,0},
	{CSS_PROP_BORDER_COLLAPSE,0,0},
	{CSS_PROP_BORDER_COLOR,0,0},
	{CSS_PROP_BORDER_LEFT,0,0},
	{CSS_PROP_BORDER_LEFT_COLOR,0,0},
	{CSS_PROP_BORDER_LEFT_STYLE,0,0},
	{CSS_PROP_BORDER_LEFT_WIDTH,0,0},
	{CSS_PROP_BORDER_RIGHT,0,0},
	{CSS_PROP_BORDER_RIGHT_COLOR,0,0},
	{CSS_PROP_BORDER_RIGHT_STYLE,0,0},
	{CSS_PROP_BORDER_RIGHT_WIDTH,0,0},
	{CSS_PROP_BORDER_SPACING,0,0},
	{CSS_PROP_BORDER_STYLE,0,0},
	{CSS_PROP_BORDER_TOP,0,0},
	{CSS_PROP_BORDER_TOP_COLOR,0,0},
	{CSS_PROP_BORDER_TOP_STYLE,0,0},
	{CSS_PROP_BORDER_TOP_WIDTH,0,0},
	{CSS_PROP_BORDER_WIDTH,0,0},
	{CSS_PROP_BOTTOM,0,1},
	{CSS_PROP_CAPTION_SIDE,0,0},
	{CSS_PROP_CLEAR,0,1},
	{CSS_PROP_CLIP,0,0},
	{CSS_PROP_COLOR,1,0},
	{CSS_PROP_CONTENT,0,0},
	{CSS_PROP_COUNTER_INCREMENT,0,0},
	{CSS_PROP_COUNTER_RESET,0,0},
	{CSS_PROP_CUE,0,0},
	{CSS_PROP_CUE_AFTER,0,0},
	{CSS_PROP_CUE_BEFORE,0,0},
	{CSS_PROP_CURSOR,0,0},
	{CSS_PROP_DIRECTION,0,0},
	{CSS_PROP_DISPLAY,0,1},
	{CSS_PROP_ELEVATION,0,0},
	{CSS_PROP_EMPTY_CELLS,0,0},
	{CSS_PROP_FILTER,0,0},
	{CSS_PROP_FLOAT,0,1},
	{CSS_PROP_FONT,1,0},
	{CSS_PROP_FONT_FAMILY,1,0},
	{CSS_PROP_FONT_SIZE,1,0},
	{CSS_PROP_FONT_SIZE_ADJUST,0,0},
	{CSS_PROP_FONT_STRETCH,0,0},
	{CSS_PROP_FONT_STYLE,1,0},
	{CSS_PROP_FONT_VARIANT,0,0},
	{CSS_PROP_FONT_WEIGHT,1,0},
	{CSS_PROP_HEIGHT,0,1},
	{CSS_PROP_IME_MODE,0,0},
	{CSS_PROP_INCLUDE_SOURCE,0,0},
	{CSS_PROP_LAYER_BACKGROUND_COLOR,1,0},
	{CSS_PROP_LAYER_BACKGROUND_IMAGE,0,0},
	{CSS_PROP_LAYOUT_FLOW,0,0},
	{CSS_PROP_LAYOUT_GRID,0,0},
	{CSS_PROP_LAYOUT_GRID_CHAR,0,0},
	{CSS_PROP_LAYOUT_GRID_CHAR_SPACING,0,0},
	{CSS_PROP_LAYOUT_GRID_LINE,0,0},
	{CSS_PROP_LAYOUT_GRID_MODE,0,0},
	{CSS_PROP_LAYOUT_GRID_TYPE,0,0},
	{CSS_PROP_LEFT,0,1},
	{CSS_PROP_LETTER_SPACING,0,0},
	{CSS_PROP_LINE_BREAK,0,0},
	{CSS_PROP_LINE_HEIGHT,0,1},
	{CSS_PROP_LIST_STYLE,0,0},
	{CSS_PROP_LIST_STYLE_IMAGE,0,0},
	{CSS_PROP_LIST_STYLE_POSITION,0,0},
	{CSS_PROP_LIST_STYLE_TYPE,0,0},
	{CSS_PROP_MARGIN,0,1},
	{CSS_PROP_MARGIN_BOTTOM,0,1},
	{CSS_PROP_MARGIN_LEFT,0,1},
	{CSS_PROP_MARGIN_RIGHT,0,1},
	{CSS_PROP_MARGIN_TOP,0,1},
	{CSS_PROP_MARKER_OFFSET,0,0},
	{CSS_PROP_MARKS,0,0},
	{CSS_PROP_MAX_HEIGHT,0,1},
	{CSS_PROP_MAX_WIDTH,0,1},
	{CSS_PROP_MIN_HEIGHT,0,1},
	{CSS_PROP_MIN_WIDTH,0,1},
	{CSS_PROP__MOZ_BINDING,0,0},
	{CSS_PROP__MOZ_BORDER_BOTTOM_COLORS,0,0},
	{CSS_PROP__MOZ_BORDER_LEFT_COLORS,0,0},
	{CSS_PROP__MOZ_BORDER_RADIUS,0,0},
	{CSS_PROP__MOZ_BORDER_RADIUS_BOTTOMLEFT,0,0},
	{CSS_PROP__MOZ_BORDER_RADIUS_BOTTOMRIGHT,0,0},
	{CSS_PROP__MOZ_BORDER_RADIUS_TOPLEFT,0,0},
	{CSS_PROP__MOZ_BORDER_RADIUS_TOPRIGHT,0,0},
	{CSS_PROP__MOZ_BORDER_RIGHT_COLORS,0,0},
	{CSS_PROP__MOZ_BORDER_TOP_COLORS,0,0},
	{CSS_PROP__MOZ_OPACITY,0,0},
	{CSS_PROP__MOZ_OUTLINE,0,0},
	{CSS_PROP__MOZ_OUTLINE_COLOR,0,0},
	{CSS_PROP__MOZ_OUTLINE_STYLE,0,0},
	{CSS_PROP__MOZ_OUTLINE_WIDTH,0,0},
	{CSS_PROP__MOZ_USER_FOCUS,0,0},
	{CSS_PROP__MOZ_USER_INPUT,0,0},
	{CSS_PROP__MOZ_USER_MODIFY,0,0},
	{CSS_PROP__MOZ_USER_SELECT,0,0},
	{CSS_PROP_ORPHANS,0,0},
	{CSS_PROP_OUTLINE,0,0},
	{CSS_PROP_OUTLINE_COLOR,0,0},
	{CSS_PROP_OUTLINE_STYLE,0,0},
	{CSS_PROP_OUTLINE_WIDTH,0,0},
	{CSS_PROP_OVERFLOW,0,0},
	{CSS_PROP_OVERFLOW_X,0,0},
	{CSS_PROP_OVERFLOW_Y,0,0},
	{CSS_PROP_PADDING,0,1},
	{CSS_PROP_PADDING_BOTTOM,0,1},
	{CSS_PROP_PADDING_LEFT,0,1},
	{CSS_PROP_PADDING_RIGHT,0,1},
	{CSS_PROP_PADDING_TOP,0,1},
	{CSS_PROP_PAGE,0,0},
	{CSS_PROP_PAGE_BREAK_AFTER,0,0},
	{CSS_PROP_PAGE_BREAK_BEFORE,0,0},
	{CSS_PROP_PAGE_BREAK_INSIDE,0,0},
	{CSS_PROP_PAUSE,0,0},
	{CSS_PROP_PAUSE_AFTER,0,0},
	{CSS_PROP_PAUSE_BEFORE,0,0},
	{CSS_PROP_PITCH,0,0},
	{CSS_PROP_PITCH_RANGE,0,0},
	{CSS_PROP_PLAY_DURING,0,0},
	{CSS_PROP_POSITION,0,1},
	{CSS_PROP_QUOTES,0,0},
	{CSS_PROP__REPLACE,0,0},
	{CSS_PROP_RICHNESS,0,0},
	{CSS_PROP_RIGHT,0,1},
	{CSS_PROP_RUBY_ALIGN,1,0},
	{CSS_PROP_RUBY_OVERHANG,0,0},
	{CSS_PROP_RUBY_POSITION ,0,0},
	{CSS_PROP_SCROLLBAR_3D_LIGHT_COLOR,0,0},
	{CSS_PROP_SCROLLBAR_ARROW_COLOR,0,0},
	{CSS_PROP_SCROLLBAR_BASE_COLOR,0,0},
	{CSS_PROP_SCROLLBAR_DARK_SHADOW_COLOR,0,0},
	{CSS_PROP_SCROLLBAR_FACE_COLOR,0,0},
	{CSS_PROP_SCROLLBAR_HIGHLIGHT_COLOR,0,0},
	{CSS_PROP_SCROLLBAR_SHADOW_COLOR,0,0},
	{CSS_PROP_SCROLLBAR_TRACK_COLOR,0,0},
	{CSS_PROP__SET_LINK_SOURCE,0,0},
	{CSS_PROP_SIZE,0,0},
	{CSS_PROP_SPEAK,0,0},
	{CSS_PROP_SPEAK_HEADER,0,0},
	{CSS_PROP_SPEAK_NUMERAL,0,0},
	{CSS_PROP_SPEAK_PUNCTUATION,0,0},
	{CSS_PROP_SPEECH_RATE,0,0},
	{CSS_PROP_STRESS,0,0},
	{CSS_PROP_TABLE_LAYOUT,0,1},
	{CSS_PROP_TEXT_ALIGN,1,0},
	{CSS_PROP_TEXT_ALIGN_LAST,1,0},
	{CSS_PROP_TEXT_AUTOSPACE,0,0},
	{CSS_PROP_TEXT_DECORATION,1,0},
	{CSS_PROP_TEXT_INDENT,0,0},	/*缩进*/
	{CSS_PROP_TEXT_JUSTIFY,0,0},
	{CSS_PROP_TEXT_KASHIDA_SPACE,0,0},
	{CSS_PROP_TEXT_OVERFLOW,0,0},
	{CSS_PROP_TEXT_SHADOW,1,0},
	{CSS_PROP_TEXT_TRANSFORM,0,0},	/*大小写转换*/
	{CSS_PROP_TEXT_UNDERLINE_POSITION,1,0},
	{CSS_PROP_TOP,0,1},
	{CSS_PROP_UNICODE_BIDI,0,0},
	{CSS_PROP__USE_LINK_SOURCE,0,0},
	{CSS_PROP_VERTICAL_ALIGN,1,0},
	{CSS_PROP_VISIBILITY,1,0},
	{CSS_PROP_VOICE_FAMILY,0,0},
	{CSS_PROP_VOLUME ,0,0},
	{CSS_PROP_WHITE_SPACE,0,0},
	{CSS_PROP_WIDOWS,0,0},
	{CSS_PROP_WIDTH,0,1},
	{CSS_PROP_WORD_BREAK,0,0},
	{CSS_PROP_WORD_SPACING,0,0},
	{CSS_PROP_WORD_WRAP,0,1},
	{CSS_PROP_WRITING_MODE,0,0},	/* 文字的书写顺序:左右|上下*/
	{CSS_PROP_UNKNOWN,0,0}
};
