/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef StructData_CONSTANTS_H
#define StructData_CONSTANTS_H

#include "StructData_types.h"



class StructDataConstants {
 public:
  StructDataConstants();

};

extern const StructDataConstants g_StructData_constants;



#endif
