/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "StructData_constants.h"



const StructDataConstants g_StructData_constants;

StructDataConstants::StructDataConstants() {
}



